data.extend({
  {
    type = "sprite",
    name = "nauvis",
    filename = "__planet-picker__/graphics/icons/nauvis.png",
    size = 512,
    scale = 1.0,
    priority = "high",
  },
  {
    type = "sprite",
    name = "gleba",
    filename = "__planet-picker__/graphics/icons/gleba.png",
    size = 512,
    scale = 1.0,
    priority = "high",
  },
  {
    type = "sprite",
    name = "fulgora",
    filename = "__planet-picker__/graphics/icons/fulgora.png",
    size = 512,
    scale = 1.0,
    priority = "high",
  },
  {
    type = "sprite",
    name = "vulcanus",
    filename = "__planet-picker__/graphics/icons/vulcanus.png",
    size = 512,
    scale = 1.0,
    priority = "high",
  },
  {
    type = "sprite",
    name = "aquilo",
    filename = "__planet-picker__/graphics/icons/aquilo.png",
    size = 512,
    scale = 1.0,
    priority = "high",
  },
  {
    type = "sprite",
    name = "unspecified_planet",
    filename = "__planet-picker__/graphics/icons/unspecified_planet.png",
    size = 512,
    scale = 1.0,
    priority = "high",
  }
})
